"""decimal for money

Revision ID: 71b9a733f34d
Revises: 7af7bc50d3ea
Create Date: 2019-08-24 16:31:52.072186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b9a733f34d'
down_revision = '7af7bc50d3ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('investment', 'max_money',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(),
               existing_nullable=True)
    op.alter_column('investment', 'min_money',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(),
               existing_nullable=True)
    op.alter_column('investor', 'max_investment',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(),
               existing_nullable=True)
    op.alter_column('investor', 'min_investment',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(),
               existing_nullable=True)
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('investor', 'min_investment',
               existing_type=sa.DECIMAL(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('investor', 'max_investment',
               existing_type=sa.DECIMAL(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('investment', 'min_money',
               existing_type=sa.DECIMAL(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('investment', 'max_money',
               existing_type=sa.DECIMAL(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
