"""investor nullable

Revision ID: 8b3709e6e287
Revises: 71b9a733f34d
Create Date: 2019-08-24 16:43:25.153101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b3709e6e287'
down_revision = '71b9a733f34d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
