"""recreated db

Revision ID: e192c04b73e0
Revises: 
Create Date: 2019-08-24 17:33:19.284351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e192c04b73e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('entrepreneur_passport', 'startup_business_plan', name='doctypeenum'), nullable=True),
    sa.Column('document_name', sa.String(), nullable=True),
    sa.Column('file', sa.Binary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('min_money', sa.DECIMAL(), nullable=True),
    sa.Column('max_money', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_id'), 'investment', ['id'], unique=False)
    op.create_table('investor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('min_investment', sa.DECIMAL(), nullable=True),
    sa.Column('max_investment', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investor_id'), 'investor', ['id'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_id'), 'tag', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('entrepreneur', 'investor', name='roles'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('entrepreneur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('patronymic', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entrepreneur_id'), 'entrepreneur', ['id'], unique=False)
    op.create_table('investor_tag',
    sa.Column('InvestorID', sa.Integer(), nullable=True),
    sa.Column('TagID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['InvestorID'], ['investor.id'], ),
    sa.ForeignKeyConstraint(['TagID'], ['tag.id'], )
    )
    op.create_table('investorinvestmenthistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('money_invested', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investorinvestmenthistory_id'), 'investorinvestmenthistory', ['id'], unique=False)
    op.create_table('passport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series', sa.String(length=4), nullable=True),
    sa.Column('number', sa.String(length=6), nullable=True),
    sa.Column('issued_code', sa.String(length=6), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_passport_id'), 'passport', ['id'], unique=False)
    op.create_table('startup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['entrepreneur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startup_id'), 'startup', ['id'], unique=False)
    op.create_table('startup_tag',
    sa.Column('StartupID', sa.Integer(), nullable=True),
    sa.Column('TagID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['StartupID'], ['startup.id'], ),
    sa.ForeignKeyConstraint(['TagID'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('startup_tag')
    op.drop_index(op.f('ix_startup_id'), table_name='startup')
    op.drop_table('startup')
    op.drop_index(op.f('ix_passport_id'), table_name='passport')
    op.drop_table('passport')
    op.drop_index(op.f('ix_investorinvestmenthistory_id'), table_name='investorinvestmenthistory')
    op.drop_table('investorinvestmenthistory')
    op.drop_table('investor_tag')
    op.drop_index(op.f('ix_entrepreneur_id'), table_name='entrepreneur')
    op.drop_table('entrepreneur')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tag_id'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_investor_id'), table_name='investor')
    op.drop_table('investor')
    op.drop_index(op.f('ix_investment_id'), table_name='investment')
    op.drop_table('investment')
    op.drop_table('document')
    # ### end Alembic commands ###
